name: AncientTrident
version: 1.1.0
main: me.alkali.trident.Trident
api-version: 1.16
authors: [ Alkali1234 ]
description: Anceint Trident

commands:
  trident:
  balance:
    aliases:
      bal
  hologram:
    description:
      Spawns a hologram
    aliases:
      gram
  shoot:
    description: TEST COMMAND 101
  hyperion:
    description: Get a Hyperion.